package count;

import javax.swing.JOptionPane;

public class testtc extends javax.swing.JFrame {
    
private boolean isNumeric(String str) {
    return str != null && str.matches("\\d+(\\.\\d+)?");
 }
private void updateCurrentAmount() {
    try {
        double twoHundreds = isNumeric(jTextField5.getText()) ? Double.parseDouble(jTextField5.getText()) : 0;
        double hundreds = isNumeric(jTextField8.getText()) ? Double.parseDouble(jTextField8.getText()) : 0;
        double fifties = isNumeric(jTextField10.getText()) ? Double.parseDouble(jTextField10.getText()) : 0;
        double twenties = isNumeric(jTextField6.getText()) ? Double.parseDouble(jTextField6.getText()) : 0;
        double tens = isNumeric(jTextField9.getText()) ? Double.parseDouble(jTextField9.getText()) : 0;
        double fives = isNumeric(jTextField11.getText()) ? Double.parseDouble(jTextField11.getText()) : 0;
        int divider = isNumeric(jTextField7.getText()) ? Integer.parseInt(jTextField7.getText()) : 1;
        double total = (200 * twoHundreds + 100 * hundreds + 50 * fifties +
                        20 * twenties + 10 * tens + 5 * fives) * divider;

        jLabel2.setText("" + total);

        // Reset to counting animation

    } catch (NumberFormatException e) {
        jLabel2.setText("Invalid input");
    }
}

 
    public testtc() {
    initComponents();

    javax.swing.event.DocumentListener listener = new javax.swing.event.DocumentListener() {
    @Override
    public void insertUpdate(javax.swing.event.DocumentEvent e) { updateCurrentAmount(); }
    @Override
    public void removeUpdate(javax.swing.event.DocumentEvent e) { updateCurrentAmount(); }
    @Override
    public void changedUpdate(javax.swing.event.DocumentEvent e) { updateCurrentAmount(); }
};

jTextField5.getDocument().addDocumentListener(listener);
jTextField6.getDocument().addDocumentListener(listener);
jTextField7.getDocument().addDocumentListener(listener);
jTextField8.getDocument().addDocumentListener(listener);
jTextField9.getDocument().addDocumentListener(listener);
jTextField10.getDocument().addDocumentListener(listener);
jTextField11.getDocument().addDocumentListener(listener);

 /*
    // Panel background
    jPanel3.setBackground(new Color(0,204,204));  // Soft teal (#009688)

    // Button colors
    jButton1.setBackground(new Color(102,255,102));  // Medium green (#4CAF50)
    jButton1.setForeground(Color.WHITE);

    jButton2.setBackground(new Color(255,51,51));  // Coral red (#E53935)
    jButton2.setForeground(Color.WHITE);

    // Label colors
    jLabel1.setForeground(new Color(33, 33, 33));    // Charcoal (#212121)

    // Optional: set text field colors for better UX
    Color textFieldBg = Color.WHITE;
    Color textFieldFg = new Color(33, 33, 33);

    jTextField5.setBackground(textFieldBg);
    jTextField6.setBackground(textFieldBg);
    jTextField7.setBackground(textFieldBg);
    jTextField8.setBackground(textFieldBg);
    jTextField9.setBackground(textFieldBg);
    jTextField10.setBackground(textFieldBg);
    jTextField11.setBackground(textFieldBg);

    jTextField5.setForeground(textFieldFg);
    jTextField6.setForeground(textFieldFg);
    jTextField7.setForeground(textFieldFg);
    jTextField8.setForeground(textFieldFg);
    jTextField9.setForeground(textFieldFg);
    jTextField10.setForeground(textFieldFg);
    jTextField11.setForeground(textFieldFg);
*/
    setResizable(false);
    setLocationRelativeTo(null);
    setTitle("Mina  Beh Count System");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Compact Display", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Mina Beh Count System :)");
        jLabel1.setToolTipText("");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 29));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 40));
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 330, 50));
        jLabel1.getAccessibleContext().setAccessibleName("minaaaaaaaaaaa");

        jButton3.setBackground(new java.awt.Color(0, 204, 204));
        jButton3.setFont(new java.awt.Font("SF Compact Display", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setText("Show history");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 46, 110, 30));

        jLabel9.setFont(new java.awt.Font("SF Compact Display", 0, 14)); // NOI18N
        jLabel9.setText("How Many At A Time");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 150, 30));

        jLabel2.setFont(new java.awt.Font("SF Compact Text", 0, 12)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 264, 40));

        jLabel3.setFont(new java.awt.Font("SF Compact Text", 0, 12)); // NOI18N
        jLabel3.setText("YOUR CURRENT BALANCE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 0, 160, 24));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("SF Compact Text", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Total Amount");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 170, 40));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("SF Compact Text", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Delete ALL");
        jButton2.setPreferredSize(new java.awt.Dimension(76, 34));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 170, 40));

        jPanel7.setLayout(new java.awt.GridBagLayout());

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("SF Compact Display", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 480;
        gridBagConstraints.ipady = 81;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 175, 0, 217);
        jPanel7.add(jLabel10, gridBagConstraints);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 15, 80, -1));
        jPanel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 9, 80, -1));

        jLabel6.setFont(new java.awt.Font("SF Compact Text", 1, 18)); // NOI18N
        jLabel6.setText("20");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 9, 47, -1));

        jLabel7.setFont(new java.awt.Font("SF Compact Display", 1, 18)); // NOI18N
        jLabel7.setText("200");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 15, -1, -1));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 15, 80, -1));
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 9, 80, -1));

        jLabel8.setFont(new java.awt.Font("SF Compact Text", 1, 18)); // NOI18N
        jLabel8.setText("10");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 47, -1));

        jLabel11.setFont(new java.awt.Font("SF Compact Display", 1, 18)); // NOI18N
        jLabel11.setText("100");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 15, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel9.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 15, 80, -1));
        jPanel9.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 9, 80, -1));

        jLabel12.setFont(new java.awt.Font("SF Compact Text", 1, 18)); // NOI18N
        jLabel12.setText("5");
        jPanel9.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 47, -1));

        jLabel13.setFont(new java.awt.Font("SF Compact Display", 1, 18)); // NOI18N
        jLabel13.setText("50");
        jPanel9.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Check all fields contain only numbers
    
    if (!isNumeric(jTextField5.getText()) ||
        !isNumeric(jTextField6.getText()) ||
        !isNumeric(jTextField7.getText()) ||
        !isNumeric(jTextField8.getText()) ||
        !isNumeric(jTextField9.getText()) ||
        !isNumeric(jTextField10.getText()) ||
        !isNumeric(jTextField11.getText())) {

        jLabel10.setText("Please enter only numbers in all fields!");
        JOptionPane.showMessageDialog(this, "Please enter only numeric values in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    jLabel10.setText("All fields are valid numbers! Ya Mina Beh");        
        try {
       
        double twoHundreds = Double.parseDouble(jTextField5.getText());
double hundreds    = Double.parseDouble(jTextField8.getText());
double fifties     = Double.parseDouble(jTextField10.getText());
double twenties    = Double.parseDouble(jTextField6.getText());
double tens        = Double.parseDouble(jTextField9.getText());
double fives       = Double.parseDouble(jTextField11.getText());

        int divider = Integer.parseInt(jTextField7.getText());

        double total = (200 * twoHundreds + 100 * hundreds + 50 * fifties +
                        20 * twenties + 10 * tens + 5 * fives) * divider;

        int id = DBConn.insertMoneyCount(
                0, // ones
                fives,
                tens,
                twenties,
                fifties,
                hundreds,
                twoHundreds,
                divider,
                total,
                java.time.LocalDate.now().toString()
        );
JOptionPane.showMessageDialog(this, "Your ID is: " +id);

        if (id != -1) {
            jLabel10.setText("# history: " + id + ""
                    + ", Total: " + total);
        } else {
            jLabel10.setText("Failed to save.");
        }

    } catch (NumberFormatException e) {
        jLabel10.setText("Invalid input!");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    jTextField5.setText("");
    jTextField6.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    jTextField10.setText("");
    jTextField11.setText("");
    jLabel10.setText("Fields cleared ya Mina Beh !!!");
     JOptionPane.showMessageDialog(this, "Welcome back, Mina Beh! Let's count again 😄", "Hello!", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    new history().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testtc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    //</editor-fold>
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new testtc().setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}